### ISSUE TITLE
Fatal error at end of ipv6 ping

### ISSUE THREAD

**Issue by aalmenar** [hybula/lookingglass#12]
Hi,

When using docker images, after ping finalization i get this error displayed:

Fatal error:  Uncaught TypeError: posix_kill(): Argument #1 ($process_id) must be of type int, string given in /var/www/html/LookingGlass.php:348
Stack trace:
#0 /var/www/html/LookingGlass.php(348): posix_kill('14', 9)
#1 /var/www/html/LookingGlass.php(182): Hybula\LookingGlass::procExecute('ping -6 -c4 -w1...', '2001:db8...')
#2 /var/www/html/backend.php(34): Hybula\LookingGlass::ping6('2001:db8..')
#3 {main}
  thrown in /var/www/html/LookingGlass.php on line 348

**Comment by MarcHagen** [comment]
@aalmenar Hi! Good catch, ive opened an PR for this. I noticed this myself to.
