### ISSUE TITLE
Missing or incorrect CSRF token.

### ISSUE THREAD

**Issue by vonlo123** [hybula/lookingglass#25]
Hi,
I have been testing around with Alma 8 and 9, nginx and php 8.0.27 and I always get the 
`Missing or incorrect CSRF token` error message.
Even with docker I get this error.

The looking glass looks great and we would love to use it. 

Any help is appreciated!

**Comment by dqos** [comment]
Hello, this was once an old bug, are you sure you are using the latest version? It should be very easy to set up.

**Comment by vonlo123** [comment]
Hi,
I am on commit 0f2c3dfd12c0e0e5a1000535924c761e2e86f989 which should be the latest.

**Comment by dqos** [comment]
Be sure to check your nginx config, this error happens when something else resets the CSRF token.

**Comment by vonlo123** [comment]
The solution to the error is to put this in the server block in the nginx config:

> location = /favicon.ico {
> try_files $uri =204;
> }
