### ISSUE TITLE
How to fully disable IPV4 in the part "Your IP"

### ISSUE THREAD

**Issue by nlkocx** [hybula/lookingglass#27]
Hey guys.

Can you disable the LG to get the user ipv6?

I don't offer ipv6, so it's pointless for them to try running an MTR on their ipv6; it will create confusion.

So I would like only the LG to get the users IPV4.

Kind regards

**Comment by dqos** [comment]
If your LG *server* doesn't have IPv6 configured, it will not show the user's IPv6. As long as your server/VM only has IPv4, it will show the visitors IPv4 address.
