### ISSUE TITLE
URL to results

### ISSUE THREAD

**Issue by anfimovir** [hybula/lookingglass#28]
Hello,

Please add the ability to provide a temporary link to the results obtained (for example, within a week).

Demo - https://lg.selectel.ru

<img width="1242" alt="Снимок экрана 2023-10-06 в 19 47 38" src="https://github.com/hybula/lookingglass/assets/10336636/5ae37083-fe61-431a-a3cd-8389ea78a8aa">

**Comment by dqos** [comment]
Nice feature, but currently too much work to implement due to the way this LG works (buffering output). Thanks for the tip.
