### ISSUE TITLE
Docker error

### ISSUE THREAD

**Issue by berndy2001** [hybula/lookingglass#29]
after  `docker-compose up`  i get this error in the browser:

```
Warning: Constant LG_CUSTOM_HEAD already defined in /var/www/html/config.php on line 20

Warning: session_name(): Session name cannot be changed after headers have already been sent in /var/www/html/LookingGlass.php on line 135
Could not start session!
```

Debian 12
Docker version 20.10.24
docker-compose version 1.29.2

and also tried with
Docker version 24.0.6
Docker Compose version v2.20.3

**Comment by dqos** [comment]
Remote line 20 from config.php and it should work, I think this is a typo. Will be fixed in next release.

**Comment by berndy2001** [comment]
Hello, thank you for your reply. I did that, but then came a PHP error - something with "explode". Anyway, I then simply took the config.dist.php with it now works.

However, I now get the error message "Missing or incorrect CSRF token" as in #25.

**Comment by dqos** [comment]
@berndy2001 are you using this nginx config? https://github.com/hybula/lookingglass/blob/main/docker/nginx/nginx.conf

**Comment by berndy2001** [comment]
I assume that, I only use the command `docker-compose up`
