### ISSUE TITLE
Uncaught TypeError: urlencode(): Argument #1 ($string) must be of type string

### ISSUE THREAD

**Issue by bkwien** [hybula/lookingglass#33]
I don't know what I'm doing wrong, but it looks like this for me.

![2023-11-04 23_18_01-Looking Glass](https://github.com/hybula/lookingglass/assets/149838277/dbf39cff-0ea4-4003-9eba-9adfc21d1211)

Sourcecode:
![2023-11-04 23_19_03-view-source_192 168 1 225_82](https://github.com/hybula/lookingglass/assets/149838277/74aa9a06-4291-4282-a84b-33b980eb6b83)

I have used these commands:
```
git clone https://github.com/hybula/lookingglass.git
cd lookingglass
docker compose up
```

**Comment by dqos** [comment]
Adjust `config.php` please.

**Comment by bkwien** [comment]
Ah ok, there are ENV variables, I didn't know that.
Ok, page loads now, but with ping, mtr and traceroute the message "Missing or incorrect CSRF token." appears.

**Comment by dqos** [comment]
@bkwien this is caused by favicon.ico being loaded. There is a PR coming for this: https://github.com/hybula/lookingglass/pull/34
I will let you know once we pushed a release for this 👍🏽

**Comment by dqos** [comment]
New release which fixes your issue: https://github.com/hybula/lookingglass/releases/tag/1.3.0
