### ISSUE TITLE
Docker - Confused on Env

### ISSUE THREAD

**Issue by ItIsSeven** [hybula/lookingglass#35]
How can I disable the Network & Speedtest sections if my LookingGlass is only for one host.
I tried to set env variables in the `docker-compose.yml` file as the readme says, but using this doesn't work:

`LG_BLOCK_NETWORK: 'false';`
`LG_BLOCK_SPEEDTEST: 'false';`

Also confused on if I set this as true: `ENABLE_CUSTOM_BLOCK`, where should the files go when using Docker, which directory?

**Comment by dqos** [comment]
The Docker part still needs some more love, but as you can see in the `config.php` not all options are moved to environment variables, still hardcoded. If you want to run this in Docker I would recommend you to edit the config file. For the custom block you will need to mount the files.

A fast fix would be not to use Docker, spin up a VM and follow the instructions, do a git pull and enjoy 😄

**Comment by ItIsSeven** [comment]
Hey, wouldn't it be appropriate this issue stays open till this is resolved, as it seems important for Docker users for those other Environment variables to be editable, thanks.
