### ISSUE TITLE
How to use custom css file

### ISSUE THREAD

**Issue by k4im** [hybula/lookingglass#42]
We're trying to deploy the application on our production server, but we want to use a custom css file.

Right now we're trying to use the **LG_CSS_OVERRIDES** but with no success.

The custom css file does not get loaded, keeping just the bootstrap loaded. 

Can someone please explain how to use custom css files?

**Comment by k4im** [comment]
I've found that the behavior only occurs when we try to use the docker version.

When the LG is used with apache or nginx, that same behavior does do not occurs.

**Comment by dqos** [comment]
The CSS override variable is not read from environment: https://github.com/hybula/lookingglass/blob/main/docker/php-fpm/src/config.php#L21

Either manually change it, or edit to get it from environment.
